pip install scipy
pip install astropy
pip install matplotlib
pip install photutils
pip install scikit-image
pip install astroquery
pip install pysimplegui
pip install opencv-python
pip install pandas
pip install scikit-learn
pip install git+https://github.com/esa/tetra3.git
